import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Check, Flag, Minus, Play, Plus, ShoppingBasket } from "lucide-react";
import { FoodImage } from "../../components/FoodImage";
import { DashboardPageShell } from "../../components/dashboard/DashboardPageShell";
import { api } from "../../services/api";
import { Recipe, RecipeMatch } from "../../types/inventory";
import { routes } from "../../types/navigation";

export function RecipeDetails({ onNavigate, recipeId }: { onNavigate: (page: string) => void; recipeId?: string }) {
  const [recipe, setRecipe] = useState<Recipe | null>(null);
  const [match, setMatch] = useState<RecipeMatch | null>(null);
  const [servings, setServings] = useState(1);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    if (!recipeId) { setError("Choose a recipe from Explore or Meals."); setLoading(false); return; }
    setLoading(true); setError("");
    try { const [recipeValue, matchValue] = await Promise.all([api<Recipe>(`/recipes/${recipeId}`), api<RecipeMatch>(`/recipe-matcher/${recipeId}/check`)]); setRecipe(recipeValue); setMatch(matchValue); setServings(recipeValue.servings); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load recipe."); }
    finally { setLoading(false); }
  }, [recipeId]);
  useEffect(() => { void load(); }, [load]);
  const startCooking = async () => { if (!recipe) return; setBusy("cook"); try { const session = await api<{id:string}>(`/cooking/start/${recipe.id}`, {method:"POST",body:JSON.stringify({servings})}); onNavigate(routes.cookingSession(session.id)); } catch(reason){setError(reason instanceof Error?reason.message:"Could not start cooking.");} finally{setBusy("");} };
  const addMeal = async () => { if (!recipe) return; setBusy("meal"); try { await api("/meal-planner",{method:"POST",body:JSON.stringify({recipeId:recipe.id,plannedDate:new Date().toISOString(),mealType:"DINNER",servings})}); onNavigate("Meals"); } catch(reason){setError(reason instanceof Error?reason.message:"Could not plan meal.");} finally{setBusy("");} };
  const generate = async () => { if (!recipe) return; setBusy("grocery"); try { const list=await api<{id:string}>(`/shopping-list/generate/from-recipe/${recipe.id}`,{method:"POST",body:JSON.stringify({servings})}); onNavigate(routes.shoppingList(list.id)); } catch(reason){setError(reason instanceof Error?reason.message:"Could not refresh grocery list.");} finally{setBusy("");} };
  const report = async () => { if (!recipe) return; const details = window.prompt("What should moderators review about this recipe?"); if (!details) return; setBusy("report"); try { await api(`/recipes/${recipe.id}/reports`, { method: "POST", body: JSON.stringify({ reason: "COMMUNITY_REPORT", details }) }); setError("Report sent to moderators. Thank you."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not report recipe."); } finally { setBusy(""); } };
  if (loading) return <DashboardPageShell activePage="Explore" onNavigate={onNavigate}><div className="p-12 text-center">Loading recipe…</div></DashboardPageShell>;
  if (!recipe) return <DashboardPageShell activePage="Explore" onNavigate={onNavigate}><div className="m-6 rounded-xl bg-red-50 p-6 text-center text-red-700" role="alert"><p>{error}</p><div className="mt-4 flex justify-center gap-4"><button onClick={()=>void load()} className="rounded-lg bg-[#064536] px-5 py-2 text-white">Try again</button><button onClick={()=>onNavigate("Explore")} className="underline">Back to recipes</button></div></div></DashboardPageShell>;
  const scale = servings / Math.max(1,recipe.servings);
  return <DashboardPageShell activePage="Explore" onNavigate={onNavigate} rootClassName="app-shell--recipe-details">
    <main className="mx-auto max-w-7xl p-4 sm:p-7"><button onClick={()=>onNavigate("Explore")} className="mb-4 flex items-center gap-2 text-sm"><ArrowLeft size={17}/> Explore recipes</button>{error?<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}
      <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(280px,.7fr)]"><div className="space-y-5"><section className="overflow-hidden rounded-3xl border bg-[#fffdf8]">{recipe.imageUrl?<FoodImage src={recipe.imageUrl} alt={recipe.name} variant="hero" priority className="h-72 w-full object-cover"/>:null}<div className="p-6"><h1 className="font-serif text-4xl">{recipe.name}</h1><p className="mt-2 text-sm text-[#646c67]">{recipe.description}</p>{recipe.catalogId ? <p className="mt-3 text-xs font-medium text-[#356052]">Seeded by {recipe.createdBy?.profile?.displayName ?? "Platform Admin"}{recipe.catalogBatch ? ` · ${recipe.catalogBatch.replace("batch_", "Batch ")}` : ""}</p> : null}<div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#edf4ef] px-3 py-1 text-xs">{match?.ingredientPresencePercentage ?? 0}% ingredients owned</span><span className={`rounded-full px-3 py-1 text-xs ${match?.canCookNow?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-800"}`}>{match?.canCookNow?"Ready to cook":match?.insufficientIngredients.length?"Some quantities are low":"Missing ingredients"}</span><span className="rounded-full bg-[#f4eee3] px-3 py-1 text-xs">{recipe.prepTimeMinutes+recipe.cookTimeMinutes} min</span><span className="rounded-full bg-[#f4eee3] px-3 py-1 text-xs">{recipe.difficulty??"Any level"}</span></div></div></section>
        <section className="rounded-2xl border bg-[#fffdf8] p-5"><h2 className="font-serif text-2xl">Cooking steps</h2><div className="mt-4 space-y-4">{recipe.steps.map((step)=><article key={step.id} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#07513f] text-xs text-white">{step.stepNumber}</span><div><p className="text-sm">{step.instruction}</p>{step.durationMinutes?<small>{step.durationMinutes} minutes</small>:null}</div></article>)}</div></section></div>
        <aside className="space-y-4"><section className="rounded-2xl border bg-[#fffdf8] p-5"><h2 className="font-serif text-xl">Servings</h2><div className="mt-3 flex items-center justify-between rounded-lg border"><button onClick={()=>setServings((value)=>Math.max(1,value-1))} className="p-3"><Minus size={15}/></button><strong>{servings}</strong><button onClick={()=>setServings((value)=>value+1)} className="p-3"><Plus size={15}/></button></div><div className="mt-4 grid gap-2"><button disabled={!!busy} onClick={()=>void startCooking()} className="flex items-center justify-center gap-2 rounded-lg bg-[#ff5f4b] p-3 text-sm text-white disabled:opacity-50"><Play size={16}/> {busy==="cook"?"Starting…":"Start cooking"}</button><button disabled={!!busy} onClick={()=>void addMeal()} className="flex items-center justify-center gap-2 rounded-lg border p-3 text-sm"><CalendarDays size={16}/> Add to meal plan</button><button disabled={!!busy} onClick={()=>void generate()} className="flex items-center justify-center gap-2 rounded-lg border p-3 text-sm"><ShoppingBasket size={16}/> Refresh grocery list</button></div></section>
        <section className="rounded-2xl border bg-[#fffdf8] p-5"><h2 className="font-serif text-xl">Ingredients</h2><div className="mt-3 divide-y">{recipe.ingredients.map((item)=>{const available=match?.availableIngredients.some((entry)=>entry.ingredientId===item.ingredientId);return <div key={item.ingredientId} className="flex items-center gap-2 py-3 text-xs"><span className={`grid h-5 w-5 place-items-center rounded-full ${available?"bg-emerald-100 text-emerald-700":"bg-amber-100"}`}>{available?<Check size={12}/>:null}</span><span className="flex-1">{item.ingredient.name}{item.isOptional?" (optional)":""}</span><strong>{Number((item.quantity*scale).toFixed(2))} {item.unit}</strong></div>})}</div></section>
        <section className="rounded-2xl border bg-[#fffdf8] p-5"><h2 className="font-serif text-xl">Nutrition</h2><div className="mt-3 grid grid-cols-2 gap-2 text-center text-xs">{[[recipe.caloriesPerServing,"cal"],[recipe.proteinPerServing,"g protein"],[recipe.carbsPerServing,"g carbs"],[recipe.fatPerServing,"g fat"]].map(([value,label])=><span key={label} className="rounded-lg bg-[#f4eee3] p-3"><strong className="block text-lg">{Math.round(Number(value))}</strong>{label}</span>)}</div><button disabled={!!busy} onClick={() => void report()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border p-2 text-xs text-[#6d746f]"><Flag size={13}/> Report recipe</button></section></aside></div>
    </main></DashboardPageShell>;
}
